[Fix] : Left and right side port of resistor
tscircuit/circuit-to-svg pull request #131
Opened 2024-11-16 14:10 UTC by AkashJana18

/attempt #122 

![image](https://github.com/user-attachments/assets/993bd12c-7639-40fb-9f07-e12875199ad6)

2024-11-17 20:24 UTC, seveibar commented on lib/sch/svg-object-fns/create-svg-objects-from-sch-component-with-symbol.ts
> +    console.log("Port Object:", port); // Debug: Log each port
```suggestion
```

2024-11-17 20:26 UTC, seveibar commented
we really don't like magic numbers, so this solution probably isn't acceptable

2024-11-17 20:26 UTC, seveibar requested changes
no magic numbers allowed. What is the underlying cause of the offset on only one side?

2024-11-17 20:31 UTC, AkashJana18 commented
> we really don't like magic numbers, so this solution probably isn't acceptable

Okay, I will be right back with better solution

2024-11-20 17:46 UTC, AkashJana18 commented
Hey @seveibar ,

After investigating the issue, I’ve identified that the root cause lies in the asymmetry of the port positions defined in the symbol itself. The slight misalignment in the coordinates causes the observed offset.
![image](https://github.com/user-attachments/assets/4fe9f46f-8837-46b1-9309-4774d5283f54)


I haven’t applied any fixes yet, but addressing this at the source (by ensuring symmetrical and consistent port positions in the symbol definition) would be the cleanest solution, avoiding the need for workarounds or hacks in the code.

Looking forward to your feedback on this approach!

2024-11-20 19:18 UTC, imrishabh18 commented
@AkashJana18 Great! I had this hunch that probably it will be on the symbol alignment but great that you showed the coordinates to prove it. It would be great if you can fix this in the schematic symbols.

2024-11-21 14:07 UTC, AkashJana18 commented
Can you @imrishabh18 please tag the file ?

2024-11-21 14:13 UTC, imrishabh18 commented
https://github.com/tscircuit/schematic-symbols/blob/main/assets/symbols/boxresistor.svg

This is the file which you can edit in inkscape tool, and align the two ports. You can then see the documentation on how to generate the files after you have edited and preview.

2024-12-03 11:18 UTC, AkashJana18 commented
So i have to download the inkscape tool to edit the boxresistor.svg and push it right @imrishabh18

2025-05-19 14:08 UTC, closed without merging